main_app/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('itinerary/', views.itinerary_index, name='index'),
    path('itinerary/me', views.my_itinerary, name='my_itinerary'),
    path('itinerary/<int:itinerary_id>/', views.itinerary_detail, name='detail'),
    path('itinerary/create/', views.ItineraryCreate.as_view(), name='itinerary_create'),
    path('itinerary/<int:pk>/update/', views.ItineraryUpdate.as_view(), name='itinerary_update'),
    path('itinerary/<int:pk>/delete/', views.ItineraryDelete.as_view(), name='itinerary_delete'),
    path('itinerary/<int:itinerary_id>/add_comment/', views.add_comment, name='add_comment'),
    path('remove_comment/<int:comment_id>/', views.remove_comment, name='remove_comment'),
    path('itinerary/<int:itinerary_id>/add_photo/', views.add_photo, name='add_photo'),
    path('photo/<int:photo_id>/delete/', views.photo_delete, name='photo_delete'),
    path('itinerary/<int:itinerary_id>/add_location/<int:location_id>', views.add_location, name='add_location'),
    path('itinerary/<int:itinerary_id>/remove_location/<int:location_id>', views.remove_location, name='remove_location'),
    path('itinerary/<int:pk>/update_locations/', views.UpdateLocations.as_view(), name='update_locations'),
    path('locations/', views.LocationList.as_view(), name='locations_index'),
    path('locations/me/', views.my_locations, name='my_locations'),
    path('locations/<int:pk>/', views.LocationDetail.as_view(), name='locations_detail'),
    path('locations/create/', views.LocationCreate.as_view(), name='locations_create'),
    path('locations/<int:pk>/update/', views.LocationUpdate.as_view(), name='locations_update'),
    path('locations/<int:pk>/delete/', views.LocationDelete.as_view(), name='locations_delete'),
    path('accounts/signup/', views.signup, name='signup'),
]

travelnow/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User
from django import forms

class Location(models.Model):
    name = models.CharField(max_length=250)
    website = models.CharField(max_length=250)
    open_hours = models.TimeField(auto_now=False, auto_now_add=False)
    closing_hours = models.TimeField(auto_now=False, auto_now_add=False)
    address = models.CharField(max_length=250)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('locations_index')
        
class Itinerary(models.Model):
    description = models.TextField(max_length=500, default='')
    city = models.CharField(max_length=100, default='Seattle')
    arrival_date = models.DateField('Arrival Date', default = date.today())
    departure_date = models.DateField('Departure Date', default = date.today())
    locations = models.ManyToManyField(Location)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.description

    def get_absolute_url(self):
        return reverse('detail', kwargs={'itinerary_id': self.id})

class Comment(models.Model):
  date = models.DateField('Posted on', default=date.today())
  content = models.TextField(max_length=500)
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  itinerary = models.ForeignKey(Itinerary, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.content} on {self.date}"

  class Meta:
    ordering = ['-date']

class Photo(models.Model):
  url = models.CharField(max_length=250)
  itinerary = models.ForeignKey(Itinerary, on_delete=models.CASCADE)

  def __str__(self):
      return f"Photo for itinerary_id: {self.itinerary_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Comment, Itinerary

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

class LocationsForm(ModelForm):
    class Meta:
        model = Itinerary
        fields = ['locations']

main_app/views.py
from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import redirect, render
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
import uuid
import boto3
import os
from .models import Itinerary, Location, Comment, Photo
from .forms import CommentForm, LocationsForm
from .validations import itinerary_belongs_to_user, location_belongs_to_user, comment_belongs_to_user, photo_belongs_to_user
from django.core.exceptions import PermissionDenied


def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def itinerary_index(request):
    itinerary = Itinerary.objects.all()
    return render(request, 'itinerary/index.html', { 'itinerary': itinerary })

@login_required
def my_itinerary(request):
    itinerary = Itinerary.objects.filter(user=request.user)
    return render(request, 'itinerary/index.html', { 'itinerary': itinerary })

@login_required
def itinerary_detail(request, itinerary_id):
    itinerary = Itinerary.objects.get(id=itinerary_id)
    locations_exclude = Location.objects.exclude(id__in=itinerary.locations.all().values_list('id'))
    comment_form = CommentForm()
    locations_form = LocationsForm()

    return render(request, 'itinerary/detail.html', {
        'itinerary': itinerary,
        'locations': locations_exclude,
        'comment_form': comment_form, 
        'locations_form': locations_form, 
        'geo_key': os.environ['GEO_KEY']
    })

class ItineraryCreate(CreateView, LoginRequiredMixin):
    model = Itinerary
    fields = ['city', 'description', 'arrival_date', 'departure_date']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class ItineraryUpdate(UserPassesTestMixin, LoginRequiredMixin, UpdateView):
    model = Itinerary
    fields = ['description', 'city', 'arrival_date', 'departure_date']

    def test_func(self):
        return itinerary_belongs_to_user(self.request.user, self.kwargs['pk'])

class ItineraryDelete(UserPassesTestMixin, LoginRequiredMixin, DeleteView):
    model = Itinerary
    success_url = '/itinerary/'

    def test_func(self):
        return itinerary_belongs_to_user(self.request.user, self.kwargs['pk'])

@login_required
def add_comment(request, itinerary_id):
  form = CommentForm(request.POST)

  if form.is_valid():
    new_comment = form.save(commit=False)
    new_comment.user = request.user
    new_comment.itinerary = Itinerary.objects.get(id=itinerary_id)
    new_comment.save()
  return redirect('detail', itinerary_id=itinerary_id)

@login_required
def remove_comment(request, comment_id):
    if not comment_belongs_to_user(request.user, comment_id):
        raise PermissionDenied()
    comment = Comment.objects.get(id=comment_id)
    itinerary_id = comment.itinerary.id
    comment.delete()
    return redirect('detail', itinerary_id=itinerary_id)

@login_required
def add_location(request, itinerary_id, location_id):
    Itinerary.objects.get(id=itinerary_id).locations.add(location_id)
    return redirect('detail', itinerary_id=itinerary_id)

@login_required
def remove_location(request, itinerary_id, location_id):
    Itinerary.objects.get(id=itinerary_id).locations.remove(location_id)
    return redirect('detail', itinerary_id=itinerary_id)

class UpdateLocations(UpdateView):
    model = Itinerary
    fields = ['locations']

class LocationList(ListView, LoginRequiredMixin):
    model = Location

@login_required
def my_locations(request):
    locations = Location.objects.filter(user=request.user)
    return render(request, 'location/my_locations.html', { 'locations': locations })

class LocationDetail(DetailView, LoginRequiredMixin):
    model = Location

class LocationCreate(CreateView, LoginRequiredMixin):
    model = Location
    fields = ['name', 'website', 'open_hours', 'closing_hours', 'address']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class LocationUpdate(UserPassesTestMixin, LoginRequiredMixin, UpdateView):
    model = Location
    fields = '__all__'

    def test_func(self):
        return location_belongs_to_user(self.request.user, self.kwargs['pk'])

class LocationDelete(UserPassesTestMixin, LoginRequiredMixin, DeleteView):
    model = Location
    success_url = '/locations/' 

    def test_func(self):
        return location_belongs_to_user(self.request.user, self.kwargs['pk']) 

@login_required
def add_photo(request, itinerary_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            itinerary = Itinerary.objects.get(id=itinerary_id)
            Photo.objects.create(url=url, itinerary=itinerary)
        except:
            print('An error occurred uploading file to s3')
    return redirect('detail', itinerary_id=itinerary_id)

@login_required
def photo_delete(request, photo_id):
    if not photo_belongs_to_user(request.user, photo_id):
        raise PermissionDenied()
    photo = Photo.objects.get(id = photo_id)
    itinerary_id = photo.itinerary.id
    photo.delete()
    return redirect('detail', itinerary_id=itinerary_id)   

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

main_app/templates/itinerary/detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<h1>Itinerary Details</h1>

<div class="row">
  <div class="col-md-12">
    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
      <div class="coll">
        <h4 class="mb-0">{{ itinerary.city }}</h4>
        <h5 class="mb-1">{{ itinerary.arrival_date }} - {{ itinerary.departure_date }}</h5>
        {% if request.user.id == itinerary.user.id %}
        <div class="card-action">
          <a href="{% url 'itinerary_update' itinerary.id %}">Edit</a>
          <a href="{% url 'itinerary_delete' itinerary.id %}">Delete</a>
        </div>
        {% endif %}

        {% for photo in itinerary.photo_set.all %}
        <img class="responsive-img card-panel"  src="{{photo.url}}">
          {% if request.user.id == itinerary.user.id %}
            <form action="{% url 'photo_delete' photo.id %}" enctype="multipart/form-data" method="POST" id="photo-form">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary btn-lg" id="photo-button">delete</button>  
            </form>
          {% else %}
            <div class="card-panel center-align">No Photos Uploaded</div>
          {% endif %}
        {% endfor %}
    
        {% if request.user.id == itinerary.user.id %}
        <div class="input-group mb-3">
          <div class="custom-file">
            <form action="{% url 'add_photo' itinerary.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
              {% csrf_token %}
              <input type="file" name="photo-file" class="custom-file-input">
              <input type="submit" class="custom-file-input" value="Upload Photo">
            </form>
          </div>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>Locations</h3>
    {% if itinerary.locations.count %}
      {% for location in itinerary.locations.all %}
        <div class="card text-center">
          <div class="loc-card">
            <div class="card-content">
              <div class="card-title">
                <p>name: {{ location.name }}</p>
                <p>website: {{location.website}}</p>
                {% if request.user.id == itinerary.user.id %}
                <form action="{% url 'remove_location' itinerary.id location.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">Remove</button>
                </form>
              </div>
            </div>
          </div>
          {% endif %}
        </div>
      {% endfor %}
    {% else %}
      <h5>No Locations Added</h5>
    {% endif %}
  </div>

  {% if request.user.id == itinerary.user.id %}
    <form method="POST" id="locationform" action="{% url 'update_locations' itinerary.id %}"> 
      {% csrf_token %}
        {{ locations_form.as_p }}
        <button type="submit" class="btn btn-secondary btn-lg">Add</button>
    </form>  
  {% endif %}
    </div>
  </div>
</div>

<div id="map"></div>

<div class="col s6">
  <div class="row d-flex justify-content-center">
    <form class="comment-form" action="{% url 'add_comment' itinerary.id %}" method="POST">
      {% csrf_token %}
      <span class="form-control me-2">{{ comment_form.as_p }}</span>
      <input type="submit" class="btn btn-primary btn-lg" value="Publish">
    </form>
  </div>
  <br>
  {% if not itinerary.comment_set.count %}
    <div class="card-panel red-text center-align">No comments yet...</div>
  {% else %}

  <div class='comments'>
  {% for comment in itinerary.comment_set.all %}
    <div class='comment'>
      <p>{{comment.user}}</p>
      <p class='content'>{{comment.content}}</p>
      <p class='date'>{{comment.date}}</p>
      {% if request.user.id == comment.user.id %}
        <a class='delete-btn' href="{% url 'remove_comment' comment.id %}">Delete</a>
      {% endif %}
    </div>
  {% endfor %}
  </div>
  {% endif %}
</div>

<script src="https://maps.googleapis.com/maps/api/js?key={{ geo_key }}"></script>

<script>

  const GEO_KEY = '{{ geo_key }}';
  const city = '{{ itinerary.city }}';
  const geoUrl = `https://maps.googleapis.com/maps/api/geocode/json?address=${city}&key=${GEO_KEY}`;

  let lat, lng, map;

  fetch(geoUrl).then(res => res.json())
    .then(results => {
      console.log(results)
      lat = results.results[0].geometry.location.lat;
      lng = results.results[0].geometry.location.lng;
      map = new google.maps.Map(document.getElementById("map"), {
        center: {lat, lng},
        zoom: 10,
        styles: [
    {
        "featureType": "all",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "weight": "2.00"
            }
        ]
    },
    {
        "featureType": "all",
        "elementType": "geometry.stroke",
        "stylers": [
            {
                "color": "#9c9c9c"
            }
        ]
    },
    {
        "featureType": "all",
        "elementType": "labels.text",
        "stylers": [
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "landscape",
        "elementType": "all",
        "stylers": [
            {
                "color": "#f2f2f2"
            }
        ]
    },
    {
        "featureType": "landscape",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#ffffff"
            }
        ]
    },
    {
        "featureType": "landscape.man_made",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#ffffff"
            }
        ]
    },
    {
        "featureType": "poi",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "all",
        "stylers": [
            {
                "saturation": -100
            },
            {
                "lightness": 45
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#eeeeee"
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "labels.text.fill",
        "stylers": [
            {
                "color": "#7b7b7b"
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "labels.text.stroke",
        "stylers": [
            {
                "color": "#ffffff"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "simplified"
            }
        ]
    },
    {
        "featureType": "road.arterial",
        "elementType": "labels.icon",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "transit",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "water",
        "elementType": "all",
        "stylers": [
            {
                "color": "#46bcec"
            },
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "water",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#c8d7d4"
            }
        ]
    },
    {
        "featureType": "water",
        "elementType": "labels.text.fill",
        "stylers": [
            {
                "color": "#070707"
            }
        ]
    },
    {
        "featureType": "water",
        "elementType": "labels.text.stroke",
        "stylers": [
            {
                "color": "#ffffff"
            }
        ]
      }
    ]
      });
    }).then(() => {
      const locations = [
        {% for location in itinerary.locations.all %}
          {address: "{{location.address}}", name: "{{location.name}}"},
        {% endfor %}
      ];
      addMarkers(locations);
    });
  
  async function addMarkers(locations){
    for (let location of locations){
      const url = `https://maps.googleapis.com/maps/api/geocode/json?address=${location.address}&key=${GEO_KEY}`;
      const results = await fetch(geoUrl).then(res => res.json());
      let lat = results.results[0].geometry.location.lat;
      let lng = results.results[0].geometry.location.lng;
      new google.maps.Marker({
        position: {lat, lng},
        map,
        title: `${location.name}`,
      });
    }
  }
  
  const formEl = document.getElementById('id_locations')
  const locations = [
        {% for location in itinerary.locations.all %}
        '{{ location.id }}', 
        {% endfor %} 
    ];

    locations.forEach(function(m) {
        const selectEl = document.getElementById('id_locations');
        let idx = 0;
        for (let option of selectEl.options) {
            if (locations.includes(option.value)) selectEl.options[idx].selected = true;
            idx++;
        }
    });
  M.FormSelect.init(formEl);

</script>

{% endblock %}

main_app/templates/itinerary/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Itinerary List</h1>

{% for it in itinerary %}
  <a href="{% url 'detail' it.id %}">
    <div class="card">
        <div class="card-content">
            {% if itinerary.all %}
                <span class="card-title"> {{ it.user }}'s Trip To {{it.city}}</span>
            {% else %}
                <span class="card-title"> No trips yet...</span>
            {% endif %}
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}